# Port no. at which this application will listen on
server.port=8181
server.error.include-message=always

# Disabling the JDBC Datasource auto-config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

project.api.url=http://localhost:9191/api/v1/projects
mailing-list.api.url=http://localhost:9191/api/v1/emails

# Spring security properties
spring.security.user.name=admin
spring.security.user.password=admin
