replicaCount: 1

image:
  repository: "krashnat922/afourathon2.0"
  tag: "projectmanagement-fe"
  pullPolicy: "Always"

config:
  #namespace: "afourathon-fe"
  #serviceAccount: "afourathon-fe"
  # This path is used to mount the application conf over init container.
  secretName: afourathon-wsr
  secretPath: "/app/env.values"
  subPath: "env.values"
       
#resources:
#  requests:
#    cpu: "2m"
#    memory: "350Mi"
#    ephemeral-storage: "2Gi"

#This is Configuration for local port inside container(POD -> kubernetes name.).
service:
  type: NodePort
  port: 8181
  targetPort: 8181
  nodePort: 30001